### ISSUE TITLE
FNaF1 and FNaF2 use

### ISSUE THREAD

**Issue by buoya42** [sussygamedeveloper/FNAF2#17]
Hello sussygamedeveloper,
I'm writing you to tell you if I can use your FNaF1 and FNaF2 games in my game website ([buoya42.github.io](https://buoya42.github.io/)).
If you want to contact me, write me in my e-mail: [buoyaa42@gmail.com](mailto:buoyaa42@gmail.com)

**Comment by sussygamedeveloper** [comment]
yeah u can use it

**Comment by buoya42** [comment]
thx!
